name: seeksoultools_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9.13
  - pip=22.2.2
  - cutadapt=4.1
  - qualimap=2.2.2d
  - samtools=1.16.1
  - star=2.7.10a
  - r-argparse=2.1.6
  - r-seurat=4.1.1
  - jinja2=3.1.2
  - lzstring=1.0.4
  - plotly=5.10.0
  - subread=2.0.1
  - bioconductor-dropletutils=1.14.2
  - pip:
    - click==8.1.3
    - cutadapt==4.1
    - loguru==0.6.0
    - numpy==1.23.3
    - pandas==1.5.0
    - pysam==0.19.1
    - scipy==1.9.1
